dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from her.views import register_view, login_view, render
from django.contrib.auth import logout


def user_logout(request):
    logout(request)
    return redirect('/my/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('/my/', permanent=False), name='dashboard'),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('my/', include('her.urls', namespace="her")),
    path("settings/", include("edit.urls", namespace="edit")),
    path('logout/', user_logout, name="logout")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

edit/urls.py
from django.urls import path
from . import views 

app_name = "edit"

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', views.quiz_users, name="quiz_users"),
    path('users/<int:pk>/', views.quiz_user_detail, name="quiz_user_detail"),

    path("exams/", views.exams, name="exams"),
    path("exams/<int:pk>/", views.exam, name="exam"),
    path('exams/<int:pk>/add/', views.add_quiz, name="add_quiz"),
    path('exams/<int:pk>/delete/', views.delete_exam, name="delete_exam"),
    path('delete/quiz/<int:quiz_id>/', views.delete_quiz, name="delete_quiz"),
    path('exams/add/', views.add_exam, name="add_exam"),
    
    path('exams/<int:pk>/<int:pk2>/', views.question_detail, name="question")
]

her/urls.py
from django.urls import path
from . import views

app_name = "her"

urlpatterns = [
    path('', views.welcome, name="index"),
    path('quiz/<str:slug>/test/<int:pk>/', views.exam_quiz_view, name="quiz"),
    path('quiz/<str:slug>/test/', views.redirect_exam_quiz, name="exam"),
    path('quiz/<str:slug>/test/<int:pk>/check', views.exam_quiz_check, name="check"),
    path('quiz/<str:slug>/result/', views.exam_result, name="result"),
]

her/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Exam(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()
    count_down = models.PositiveBigIntegerField(default=0)  # in minutes
    quizzes_length = models.PositiveBigIntegerField(default=0)
    private = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def set_quiz_length(self):
        self.quizzes_length = len(Quiz.objects.filter(exam=self))
        self.save()
        return self.quizzes_length

    def __str__(self):
        return self.name


class EditorUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    quiz_created = models.IntegerField(default=0)
    quizzes = models.ManyToManyField('Quiz', blank=True)

    def __str__(self):
        return self.user.username if self.user.username else self.user.first_name


class QuizUser(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(help_text='Enter your email')
    password = models.CharField(max_length=100, blank=True)
    quiz_passed = models.IntegerField(default=0)
    verified = models.BooleanField(default=False)
    passed_exams = models.ManyToManyField('Exam', blank=True)
    point_score = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Result(models.Model):
    user = models.ForeignKey(QuizUser, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    finished_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.name} - {self.exam.name}'


class UserAnswer(models.Model):
    user = models.ForeignKey(QuizUser, on_delete=models.CASCADE)
    answer = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.answer


class Quiz(models.Model):
    question = models.CharField(max_length=255)
    answer = models.CharField(max_length=255)
    user_answer = models.ManyToManyField(
        UserAnswer, blank=True) 
    exam = models.ForeignKey(
        Exam, on_delete=models.CASCADE, null=True, default=None)
    species = models.ForeignKey('QuizType', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "Quizes"


class QuizOption(models.Model):
    option = models.CharField(max_length=255)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    is_true = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.option


class QuizType(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

her/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from her.models import QuizUser, Quiz, QuizOption, Exam, Result, UserAnswer
from django.contrib.auth import login
from django.contrib.auth.models import User
from datetime import datetime
from json import loads
import requests
from .config import CHAT_ID, BOT_TOKEN
CHAT_ID = str(CHAT_ID)
BOT_TOKEN = str(BOT_TOKEN)

SPLITTER = "_"
# Create your views here.


def welcome(request):
    exams = Exam.objects.filter(private=False)
    [x.set_quiz_length() for x in exams]
    context = {
        'exams': exams,
    }
    return render(request, 'her/welcome.html', context)


def exam_quiz_view(request, slug, pk):
    if request.method == 'POST':
        data = request.POST
        name = data['username']
        quiz_user = QuizUser.objects.create(
            name=name, created_at=datetime.now(), updated_at=datetime.now())
        quiz_user.save()
        result = Result.objects.create(user=quiz_user, exam=Exam.objects.get(
            slug=slug))
        result.save()
        request.session['quiz_user'] = quiz_user.id
        try:
            user = User.objects.create_user(name, '', '')
        except:
            user = User.objects.create_user(
                name + SPLITTER + str(quiz_user.id), '', '')
        user.save()
        login(request, user)
        return redirect('/my/quiz/' + slug + '/' + 'test/')
    is_last = False
    exam = Exam.objects.get(slug=slug)
    quiz = Quiz.objects.get(pk=pk, exam=exam)
    options = QuizOption.objects.filter(quiz=quiz)
    print(options)
    last_quiz = Quiz.objects.filter(
        exam=Exam.objects.get(slug=slug)).order_by('-id')[0]

    if quiz.id == last_quiz.id:
        is_last = True

    context = {
        'quiz': quiz,
        'options': options,
        'exam': exam, 'is_last': is_last
    }
    if not request.user.is_authenticated:
        return redirect('/my/quiz/' + slug + '/' + 'test/')
    return render(request, 'her/quiz.html', context)


def exam_quiz_check(request, slug, pk):
    quiz_user = QuizUser.objects.get(pk=request.session['quiz_user'])
    exam = Exam.objects.get(slug=slug)
    quiz = Quiz.objects.get(pk=pk, exam=exam)
    result = Result.objects.get(
        user=quiz_user, exam=Exam.objects.get(slug=slug))
    if request.method == 'GET' and loads(request.GET.get("data")).get("answer"):
        data = request.GET
        data = loads(data.get("data"))
        user_answer = data['answer']
        result.quiz = quiz
        result.save()
        useranswer = UserAnswer.objects.create(
            user=quiz_user, answer=user_answer)
        useranswer.save()
        print('user', useranswer)
        quiz.user_answer.add(useranswer)
        result.score += 1 if quiz.answer == user_answer else 0
        result.save()
        exam_quizzes = Quiz.objects.filter(exam=exam)
        # if quiz.id == exam_quizzes.order_by('-id')[0].id:
        #     result.passed_exams.add(exam)
        #     result.save()
        #     return JsonResponse({'status': 'passed'})
        current = exam_quizzes.get(id=pk)
        all_ids = []
        for x in exam_quizzes:
            all_ids.append(x.id)

        try:
            next_id = all_ids[all_ids.index(current.id) + 1]
            next_quiz = Quiz.objects.get(id=next_id)
        except:
            next_quiz = None
        if next_quiz:
            return JsonResponse({"next_quiz_url": '/my/quiz/' + slug + '/' + 'test/' + str(next_quiz.id) + '/', "next_quiz_id": next_quiz.id, 'quiz_user': quiz_user.name})
        else:
            quiz_user.quiz_passed += 1
            quiz_user.passed_exams.add(exam)
            quiz_user.save()
            # send message to telegram with api.telegram.org
            # message text should be like this: User {name} passed exam {exam} with score {score} out of {quizzes_length}
            message = 'User "' + quiz_user.name + '" passed exam "' + exam.name + '" with score ' + str(result.score) + ' out of ' + str(exam.quizzes_length) + '" at "' + datetime.now().strftime("%d/%m/%Y %H:%M") + '"'
            url = 'https://api.telegram.org/bot' + BOT_TOKEN + '/sendMessage?chat_id=' + CHAT_ID + '&text=' + message
            try:
                requests.get(url)
            except (ConnectionError, ConnectionAbortedError, ConnectionRefusedError, ConnectionResetError):
                print("CONNECTION ERROR ON SENDING MESSAGE TO THE GROUP")
            return JsonResponse({"exam_result_url": '/my/quiz/' + slug + '/' + 'result/', "quiz_user": request.user.username})

    result.score = 0
    result.save()
    print(result.score)
    return redirect('/my/quiz/' + slug + '/' + 'test/1/')


def redirect_exam_quiz(request, slug):
    if request.user.is_authenticated:
        url = 'https://api.telegram.org/bot' + BOT_TOKEN + '/sendMessage?chat_id=' + CHAT_ID + '&text=User "' + request.user.username + '" started exam "' + Exam.objects.get(slug=slug).name + '" at "' + datetime.now().strftime("%d/%m/%Y %H:%M") + '"'
        try:
            requests.get(url)
        except:
            print("CONNECTION ERROR ON SENDING MESSAGE TO THE GROUP")
        quiz_user = QuizUser.objects.get(pk=request.session['quiz_user'])
        result = Result.objects.get(
            user=quiz_user, exam=Exam.objects.get(slug=slug))
        result.score = 0
        quizzes = Quiz.objects.filter(exam=Exam.objects.get(slug=slug))
        for quiz in quizzes.all():
            for answer in quiz.user_answer.all():
                if answer.user.id == quiz_user.id:
                    answer.delete()
        result.save()
        first_quiz_id = Quiz.objects.filter(
            exam=Exam.objects.get(slug=slug)).first().id
        return redirect(str(first_quiz_id) + '/')
    else:
        return render(request, 'her/start.html')


def exam_result(request, slug):
    print(QuizUser.objects.get(
        id=request.session['quiz_user']).passed_exams.all())
    exam = Exam.objects.get(slug=slug)
    result = Result.objects.get(user=QuizUser.objects.get(
        id=request.session['quiz_user']), exam=exam)
    quizzes = Quiz.objects.filter(exam=exam)
    f = exam.quizzes_length - result.score
    if f < 0:
        f = 0
    context = {
        'exam': exam,
        'result': result,
        'quizzes': quizzes,
        'f': f
    }
    return render(request, 'her/result.html', context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect("/my/")
    return render(request, 'her/login.html')


def register_view(request):
    return render(request, 'her/register.html')

her/templates/settings/exam.html
{% extends 'her/base.html' %} {% block content %} {% csrf_token %}
<div class="container">
  <div class="quiz-box">
    <div class="quiz-title">
      <span>{{ exam.name }}</span>
    </div>
    <div class="content">
      <p>{{ exam.description }}</p>
      <div class="answers">
        {% for quiz in quizzes %}
        <a href="{% url 'edit:question' exam.id quiz.id %}" class="no-link">
          <div class="option" data-quiz-id="{{quiz.id}}">
            <span>{{ quiz.question }}</span>
          </div>
        </a>
        {% endfor %}
      </div>
      <div class="add mt">
          <a href="{% url 'edit:add_quiz' exam.id  %}" class="side-btn">
          <button class="button"><span class="icon"><i class="fas fa-plus"></i></span><span class="text">Add Question</span></button>
        </a>
      </div>
      <div class="delete">
          <a href="{% url 'edit:delete_exam' exam.id %}" class="side-btn">
          <button class="button button-danger"><span class="icon"><i class="fas fa-trash-can"></i></span><span class="text">Delete this exam</span></button>
        </a>
      </div>
    </div>
  </div>
</div>
<script>
  var csrf_token = document.querySelector('[name="csrfmiddlewaretoken"]').value;
  var default_headers = {
    "X-CSRFToken": csrf_token,
    "Content-Type": "application/json",
  };
  function deleteQuiz(id) {
    var headers = Object.assign({}, default_headers);
    headers["X-METHOD"] = "DELETE";
    fetch("/settings/" + "delete/quiz/" + id + "/", {
      method: "POST",
      headers: headers,
    }).then(function (response) {
      if (response.ok) {
        document.querySelector('[data-quiz-id="' + id + '"]').remove();
      }
    });
  }
  document.querySelectorAll(".answers .option").forEach(function (option) {
    option.addEventListener("dblclick", function () {
      var id = option.getAttribute("data-quiz-id");
      deleteQuiz(id);
    });
  });
</script>
{% endblock %}

{% block title %}
<title>Exam: {{ exam.name }}</title>
{% endblock title %}

her/templates/settings/exams.html
{% extends 'her/base.html' %} {% block content %}
<div class="container">
  <div class="quiz-box">
    <div class="quiz-title">
      <span class="marked">Exams</span>
    </div>
    <div class="content">
      {% if exams|length == 0 %}
      <span>Currently you have no exams</span>
      {% else %}
      <div class="answers">
        {% for exam in exams %}
        <a href="{% url 'edit:exam' exam.id %}" class="no-link">
          <div class="option">
            <span>{{ exam.name }}</span>
          </div>
        </a>
        {% endfor %}
      </div>
      {% endif %}
      <div class="mt-2">
        <a href="{% url 'edit:add_exam' %}">
          <button class="button">Create Exam</button>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block title %}
<title>Exams</title>
{% endblock title %}

her/templates/settings/index.html
{% extends 'her/base.html' %} {% block content %}
<div class="container">
  <div class="quiz-box">
    <div class="quiz-title">
      <span>Settings</span>
    </div>
    <div class="content">
      <div class="row" style="display: flex; gap: 100px">
        <a href="{% url 'edit:exams' %}" class="no-link" style="width: 50%">
          <div  class="col d-center block" style="width: 100%">
            <div class="icon">
              <i class="fa-solid fa-file-invoice fa-2x"></i>
            </div>
          </div>
          <span>Exams</span>
        </a>
        <a href="{% url 'edit:quiz_users' %}" class="no-link" style="width: 50%">
          <div class="col d-center block" style="width: 100%">
            <div class="icon">
              <i class="fa-solid fa-user-graduate fa-2x"></i>
            </div>
          </div>
          <span>Users</span>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block title %}
<title>Quiz admin panel</title>
{% endblock title %}

her/templates/settings/new_question.html
{% extends 'her/base.html' %} {% block content %} {% csrf_token %}
<div class="blur-container">
</div>
<div class="container">
  <div class="quiz-box zoomIn">
    <div class="quiz-title">
      <span>Add Quiz to <span class="marked"><a href="{% url 'edit:exam' exam.id %}" class="link">{{ exam.name }}</a></span></span>
    </div>
    <div class="content">
      <div class="answers add-quiz">
        <div class="field">
          <input
            type="text"
            id="question"
            class="option option-input"
            name="question"
            placeholder="Question"
            style="width: 100%"
            tabindex="1"
          />
          <div class="d-flex gap-1  p-relative">
            <select class="option option-input mt" id="questionTypes" name="question_type">
              <option value="" selected disabled>Select Type</option>
              {% for type in types %}
              <option value="{{ type.name }}">{{ type.name }}</option>
              {% endfor %}
            </select>
            <input class="option" placeholder="Enter a name" id="questionType">
            <button class="option mt" id="addQuestionTypeButton" data-send="false">+</button>
          </div>
        </div>
        <div class="options animation">
          <div class="field remove-animation">
            <div class="option _">
              <div>
                <input type="radio" name="answer" id="answer" />
              </div>
              <div>
                <input
                  name="option"
                  id="option"
                  data-sent="false"
                  placeholder="option"
                  tabindex="2"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="field" style="display: flex">
          <button class="button button-outline" style="width: 100%" id="add">
            <span>Add Option +</span>
          </button>
        </div>
        <div class="field">
          <button class="button" id="send">
            <span>create</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  const URL = '{% url "edit:add_quiz" exam.id %}';
  const addButtton = document.querySelector("#add");
  const csrf_token = document.querySelector("[name=csrfmiddlewaretoken]").value;
  const sendButton = document.querySelector("#send");
  const modalContainer = document.querySelector(".blur-container");
  const default_headers = {
    Accept: "application/json",
    "Content-Type": "application/json",
    "X-Requested-With": "XMLHttpRequest",
    "X-CSRFToken": csrf_token,
  };

  addQuestionTypeButton.addEventListener("click", function () {
    modalContainer.classList.toggle("show");
    addQuestionTypeButton.style = 'position: relative; z-index: 2;';
    questionType.classList.toggle('show')    
    if (addQuestionTypeButton.dataset.send == 'true') {
      var name = questionType.value;
      var old_question_types = Array.from(document.querySelector("#questionTypes").children);
      var l = false;
      old_question_types.forEach(option => {
        if (name.trim().toLowerCase() == option.value) {
          l = true
        }
      })
      if (l) {
        return;
      } else {
        fetch(URL, {
          method: "POST",
          headers: default_headers,
          body: JSON.stringify({
            data: {
              name: name
            }
          })
        }).then(response => response.json()).then(data => {
          if (data.status == 'ok') {
            questionType.value = '';
            var option = document.createElement('option');
            option.value = data.name;
            option.innerText = data.name;
            document.querySelector("#questionTypes").appendChild(option);
          } else {
            throw Error("Error on posting data to: ", URL)
          }
        })
      }
    }
    addQuestionTypeButton.dataset.send == 'false' ? addQuestionTypeButton.dataset.send = 'true' : addQuestionTypeButton.dataset.send = 'false'
  })
  questionTypes.onchange = function (event) {
    if (event.target.value == "fill_blank") {
      addButtton.setAttribute("disabled", "")
    } else {
      addButtton.removeAttribute('disabled')
    }
  }
  addButtton.onclick = add;
  window.onkeyup = function (e) {
    if (e.ctrlKey && e.keyCode == 13) {
      add();
    }
  };
  function add() {
    var container = document.querySelector(".options");
    var tabindex = container.querySelectorAll(".option").length + 2;
    var template = `
          <div class="option _">
            <div>
              <input type="radio" name="answer" id="answer" />
            </div>
            <div>
              <input
                name="option"
                id="option"
                data-sent="false"
                placeholder="option"
                tabindex="${tabindex}"
              />
            </div>
          </div>
       `;
    var field = document.createElement("div");
    field.className = "field mt";
    field.innerHTML = template;
    container.appendChild(field);
    setTimeout(function () {
      field.classList.add("remove-animation");
    }, 1);
  }

  sendButton.onclick = function () {
    var question = document.querySelector("#question").value;
    var options = document.querySelectorAll(".option._");
    var questionType = document.querySelector('#questionTypes').value;
    var answers = [];
    var correct = [];
    options.forEach(function (option) {
      var answer = option.querySelector("#answer").checked;
      var option = option.querySelector("#option").value;
      if (answer) {
        correct.push(option);
      }
      answers.push(option);
    });
    var data = {
      data: {
        question: question,
        answers: answers,
        correct: correct,
        question_type: questionType
      },
    };
    if (
      data.data.question &&
      data.data.answers.length > 0 &&
      data.data.correct.length > 0 && 
      data.data.question_type
    ) {
      fetch(URL, {
        method: "POST",
        headers: default_headers,
        body: JSON.stringify(data),
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (data) {
          if (data.ok) {
            location.reload();
          }
        });
    } else {
      alert("Please fill all fields");
    }
  };
</script>
{% endblock %} {% block title %}
<title>Create a new question</title>
{% endblock title %}

her/templates/settings/question.html
{% extends 'her/base.html' %} {% block content %} {% csrf_token %}
<div class="blur-container">
</div>
<div class="container">
  <div class="quiz-box zoomIn">
    <div class="quiz-title">
      <span>Update Question in <span class="marked"><a href="{% url 'edit:exam' exam.id %}" class="link">{{ exam.name }}</a></span></span>
    </div>
    <div class="content">
      <div class="answers add-quiz">
        <div class="field">
          <label for="question">Question</label>

          <input
            type="text"
            id="question"
            class="option option-input mt"
            name="question"
            placeholder="Question"
            style="width: 100%"
            tabindex="1"
            value="{{ question.question }}"
          />
          <div class="field mt-1">
            <label for="questionType">Question type</label>
            <div class="d-flex gap-1  p-relative">
              <select class="option option-input  mt" id="questionTypes" name="question_type">
                {% for type in types %}
                <option {% if question.species.name == type.name %}selected{% endif %}>{{ type.name }}</option>
                {% endfor %}
              </select>
              <input class="option" placeholder="Enter a name" id="questionType">
              <button class="option mt" id="addQuestionTypeButton" data-send="false">+</button>
            </div>
          </div>
        </div>
        <div class="options animation">
          <label>Options</label>
            {% for option in options %}
            <div class="field remove-animation mt">
            <div class="option _">
                <div>
                  <input type="radio" name="answer" id="answer" {% if option.option == question.answer%}checked{%endif%}/>
                </div>
                <div>
                  <input
                    name="option"
                    id="option"
                    data-sent="false"
                    placeholder="option"
                    tabindex="2"
                    value="{{option.option}}"
                  />
                </div>
              </div>
            </div>
            {% endfor %}
            <div class='new mt'>
                <hr />
            </div>
        </div>

        <div class="field" style="display: flex">
          <button class="button button-outline" style="width: 100%" id="add">
            <span>+</span>
          </button>
        </div>
        <div class="field">
          <button class="button" id="update">
            <span>update</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  const URL = '{% url "edit:add_quiz" exam.id %}';
  const addButtton = document.querySelector("#add");
  const csrf_token = document.querySelector("[name=csrfmiddlewaretoken]").value;
  const updateButton = document.querySelector("#update");
  const modalContainer = document.querySelector(".blur-container");
  const default_headers = {
    Accept: "application/json",
    "Content-Type": "application/json",
    "X-Requested-With": "XMLHttpRequest",
    "X-CSRFToken": csrf_token,
  };

  addQuestionTypeButton.addEventListener("click", function () {
    modalContainer.classList.toggle("show");
    addQuestionTypeButton.style = 'position: relative; z-index: 2;';
    questionType.classList.toggle('show')    
    if (addQuestionTypeButton.dataset.send == 'true') {
      var name = questionType.value;
      var old_question_types = Array.from(document.querySelector("#questionTypes").children);
      var l = false;
      old_question_types.forEach(option => {
        if (name.trim().toLowerCase() == option.value) {
          l = true
        }
      })
      if (l) {
        console.log('l')
        return;
      } else {
        fetch(URL, {
          method: "POST",
          headers: default_headers,
          body: JSON.stringify({
            data: {
              name: name
            }
          })
        }).then(response => response.json()).then(data => {
          if (data.status == 'ok') {
            questionType.value = '';
            var option = document.createElement('option');
            option.value = data.name;
            option.innerText = data.name;
            document.querySelector("#questionTypes").appendChild(option);
          } else {
            throw Error("Error on posting data to: ", URL)
          }
        })
      }
    }
    addQuestionTypeButton.dataset.send == 'false' ? addQuestionTypeButton.dataset.send = 'true' : addQuestionTypeButton.dataset.send = 'false'
  })

  addButtton.onclick = add;
  window.onkeyup = function (e) {
    if (e.ctrlKey && e.keyCode == 13) {
      add();
    }
  };
  function add() {
    var container = document.querySelector(".options .new");
    var tabindex = container.querySelector(".option") ? +container.querySelector('.option').getAttribute('tabindex') + 1 : 1;
    var template = `
          <div class="option _">
            <div>
              <input type="radio" name="answer" id="answer" />
            </div>
            <div>
              <input
                name="option"
                id="option"
                data-sent="false"
                placeholder="option"
                tabindex="${tabindex}"
              />
            </div>
          </div>
       `;
    var field = document.createElement("div");
    field.className = "field mt";
    field.innerHTML = template;
    container.appendChild(field);
    setTimeout(function () {
      field.classList.add("remove-animation");
    }, 1);
  }
  var $data = {
    data: {
      question: "{{ question.question }}",
      questionType: document.querySelector("#questionTypes").value,
      options: Array.from(document.querySelectorAll(".option input:not([type='checkbox'])")).map(e=>e.value),
    }
  }
  console.log($data)

  // updateButton.onclick = function () {
  //   var question = document.querySelector("#question").value;
  //   var options = document.querySelectorAll(".option._");
  //   var questionType = document.querySelector('#questionTypes').value;
  //   var answers = [];
  //   var correct = [];
  //   options.forEach(function (option) {
  //     var answer = option.querySelector("#answer").checked;
  //     var option = option.querySelector("#option").value;
  //     if (answer) {
  //       correct.push(option);
  //     }
  //     answers.push(option);
  //   });
  //   var data = {
  //     data: {
  //       question: question,
  //       answers: answers,
  //       correct: correct,
  //       question_type: questionType
  //     },
  //   };
  //   if (
  //     data.data.question &&
  //     data.data.answers.length > 0 &&
  //     data.data.correct.length > 0 && 
  //     data.data.question_type
  //   ) {
  //     fetch(URL, {
  //       method: "POST",
  //       headers: default_headers,
  //       body: JSON.stringify(data),
  //     })
  //       .then(function (response) {
  //         return response.json();
  //       })
  //       .then(function (data) {
  //         if (data.ok) {
  //           location.reload();
  //         }
  //       });
  //   } else {
  //     alert("Please fill all fields");
  //   }
  // };
</script>
{% endblock %} {% block title %}
<title>Update question: {{ question.question|truncatewords:"2"}}</title>
{% endblock title %}

her/templates/settings/quiz_user_detail.html
{% extends 'her/base.html' %} {% block content %}
<div class="container">
  <div class="quiz-box">
    <div class="quiz-title">
      <span>{{quiz_user.name}}</span>
    </div>
    <div class="content">
      <div class="answers" style="margin-bottom: 10px">
        <div class="option for-data" data-for="email">
          <span>{{quiz_user.email}}</span>
        </div>

        <div class="option for-data" data-for="exams">
          {% for passed in quiz_user.passed_exams.all %}
          <a href="{% url 'her:exam' passed.slug %}"
            ><span>{{passed.name}}</span></a
          >
          {% endfor %}
        </div>

        <div class="option for-data" data-for="score">
          <span>{{quiz_user.point_score}}</span>
        </div>

        {% comment %} verified {% endcomment %}
        <div class="option for-data" data-for="verified">
          <span>{{quiz_user.verified}}</span>
        </div>
      </div>
      <span style="text-align: left"
        >Joined at {{ quiz_user.created_at|date }}</span
      >
    </div>
  </div>
</div>
{% endblock %}
{% block title %}
<title>Details: {{ quiz_user.name }}</title>
{% endblock title %}